/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HodRouteImport } from './routes/hod'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoordinatorRouteImport } from './routes/coordinator'
import { Route as ChiefMentorRouteImport } from './routes/chief-mentor'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtrsIndexRouteImport } from './routes/atrs.index'
import { Route as AtrsNewRouteImport } from './routes/atrs.new'
import { Route as AtrsAtrIdRouteImport } from './routes/atrs.$atrId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HodRoute = HodRouteImport.update({
  id: '/hod',
  path: '/hod',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorRoute = CoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiefMentorRoute = ChiefMentorRouteImport.update({
  id: '/chief-mentor',
  path: '/chief-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtrsIndexRoute = AtrsIndexRouteImport.update({
  id: '/atrs/',
  path: '/atrs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtrsNewRoute = AtrsNewRouteImport.update({
  id: '/atrs/new',
  path: '/atrs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AtrsAtrIdRoute = AtrsAtrIdRouteImport.update({
  id: '/atrs/$atrId',
  path: '/atrs/$atrId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/chief-mentor': typeof ChiefMentorRoute
  '/coordinator': typeof CoordinatorRoute
  '/dashboard': typeof DashboardRoute
  '/hod': typeof HodRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/atrs/$atrId': typeof AtrsAtrIdRoute
  '/atrs/new': typeof AtrsNewRoute
  '/atrs/': typeof AtrsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/chief-mentor': typeof ChiefMentorRoute
  '/coordinator': typeof CoordinatorRoute
  '/dashboard': typeof DashboardRoute
  '/hod': typeof HodRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/atrs/$atrId': typeof AtrsAtrIdRoute
  '/atrs/new': typeof AtrsNewRoute
  '/atrs': typeof AtrsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/chief-mentor': typeof ChiefMentorRoute
  '/coordinator': typeof CoordinatorRoute
  '/dashboard': typeof DashboardRoute
  '/hod': typeof HodRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/atrs/$atrId': typeof AtrsAtrIdRoute
  '/atrs/new': typeof AtrsNewRoute
  '/atrs/': typeof AtrsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/approvals'
    | '/chief-mentor'
    | '/coordinator'
    | '/dashboard'
    | '/hod'
    | '/login'
    | '/notifications'
    | '/signup'
    | '/team'
    | '/atrs/$atrId'
    | '/atrs/new'
    | '/atrs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/approvals'
    | '/chief-mentor'
    | '/coordinator'
    | '/dashboard'
    | '/hod'
    | '/login'
    | '/notifications'
    | '/signup'
    | '/team'
    | '/atrs/$atrId'
    | '/atrs/new'
    | '/atrs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/approvals'
    | '/chief-mentor'
    | '/coordinator'
    | '/dashboard'
    | '/hod'
    | '/login'
    | '/notifications'
    | '/signup'
    | '/team'
    | '/atrs/$atrId'
    | '/atrs/new'
    | '/atrs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApprovalsRoute: typeof ApprovalsRoute
  ChiefMentorRoute: typeof ChiefMentorRoute
  CoordinatorRoute: typeof CoordinatorRoute
  DashboardRoute: typeof DashboardRoute
  HodRoute: typeof HodRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  SignupRoute: typeof SignupRoute
  TeamRoute: typeof TeamRoute
  AtrsAtrIdRoute: typeof AtrsAtrIdRoute
  AtrsNewRoute: typeof AtrsNewRoute
  AtrsIndexRoute: typeof AtrsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hod': {
      id: '/hod'
      path: '/hod'
      fullPath: '/hod'
      preLoaderRoute: typeof HodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator': {
      id: '/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof CoordinatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chief-mentor': {
      id: '/chief-mentor'
      path: '/chief-mentor'
      fullPath: '/chief-mentor'
      preLoaderRoute: typeof ChiefMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atrs/': {
      id: '/atrs/'
      path: '/atrs'
      fullPath: '/atrs/'
      preLoaderRoute: typeof AtrsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atrs/new': {
      id: '/atrs/new'
      path: '/atrs/new'
      fullPath: '/atrs/new'
      preLoaderRoute: typeof AtrsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atrs/$atrId': {
      id: '/atrs/$atrId'
      path: '/atrs/$atrId'
      fullPath: '/atrs/$atrId'
      preLoaderRoute: typeof AtrsAtrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApprovalsRoute: ApprovalsRoute,
  ChiefMentorRoute: ChiefMentorRoute,
  CoordinatorRoute: CoordinatorRoute,
  DashboardRoute: DashboardRoute,
  HodRoute: HodRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  SignupRoute: SignupRoute,
  TeamRoute: TeamRoute,
  AtrsAtrIdRoute: AtrsAtrIdRoute,
  AtrsNewRoute: AtrsNewRoute,
  AtrsIndexRoute: AtrsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
